baseline10K:
  seed: 1042
  N: 10000
baseline100K:
  seed: 2042
  N: 100000
baseline100K_sample5K:
  seed: 2042
  N: 100000
  ascertainment:
    N_sample: 5000
baseline100K_sample50K:
  seed: 2042
  N: 100000
  ascertainment:
    N_sample: 50000
baseline1M:
  seed: 3042
  N: 1000000
  analysis:
    skip_ne_coancestry: true
baseline2M:
  seed: 99042
  N: 2000000
  analysis:
    skip_ne_coancestry: true
baseline10M:
  seed: 10042
  N: 10000000
  analysis:
    skip_ne_coancestry: true
