beck_adhd:
  seed: 40000
  N: 1000000
  phenotype:
    trait1:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 2.88737
        sigma: 0.658447
        prevalence:
          female: 0.048193
          male: 0.083224
      beta: 0.0
      beta_sex: 0.5003
    trait2:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 2.88737
        sigma: 0.658447
        prevalence:
          female: 0.048193
          male: 0.083224
      beta: 0.0
      beta_sex: 0.5003
  pedigree:
    trait1:
      C: 0.0
      E: 0.5
    trait2:
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
beck_an:
  seed: 41000
  N: 1000000
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 16.2949
        cip_k: 0.375793
        prevalence:
          female: 0.0333
          male: 0.001012
      beta: 0.7985
      beta_sex: 0.5357
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 16.2949
        cip_k: 0.375793
        prevalence:
          female: 0.0333
          male: 0.001012
      beta: 0.7985
      beta_sex: 0.5357
  pedigree:
    trait1:
      C: 0.0
      E: 0.5
    trait2:
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
beck_any:
  seed: 42000
  N: 1000000
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 0.0
        cip_k: 0.09746
        prevalence:
          female: 0.461393
          male: 0.310272
      beta: 0.2143
      beta_sex: 0.3757
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 0.0
        cip_k: 0.09746
        prevalence:
          female: 0.461393
          male: 0.310272
      beta: 0.2143
      beta_sex: 0.3757
  pedigree:
    trait1:
      C: 0.0
      E: 0.5
    trait2:
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
beck_apd:
  seed: 43000
  N: 1000000
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 26.8445
        cip_k: 0.175111
        prevalence:
          female: 0.002997
          male: 0.012299
      beta: 0.8692
      beta_sex: -0.0594
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 26.8445
        cip_k: 0.175111
        prevalence:
          female: 0.002997
          male: 0.012299
      beta: 0.8692
      beta_sex: -0.0594
  pedigree:
    trait1:
      C: 0.0
      E: 0.5
    trait2:
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
beck_au:
  seed: 44000
  N: 1000000
  phenotype:
    trait1:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 3.86639
        sigma: 0.477996
        prevalence:
          female: 0.028329
          male: 0.051935
      beta: 0.0
      beta_sex: 0.1122
    trait2:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 3.86639
        sigma: 0.477996
        prevalence:
          female: 0.028329
          male: 0.051935
      beta: 0.0
      beta_sex: 0.1122
  pedigree:
    trait1:
      C: 0.0
      E: 0.5
    trait2:
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
beck_bd:
  seed: 45000
  N: 1000000
  phenotype:
    trait1:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 3.59391
        sigma: 0.44395
        prevalence:
          female: 0.022725
          male: 0.016852
      beta: 0.0
      beta_sex: -0.3359
    trait2:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 3.59391
        sigma: 0.44395
        prevalence:
          female: 0.022725
          male: 0.016852
      beta: 0.0
      beta_sex: -0.3359
  pedigree:
    trait1:
      C: 0.0
      E: 0.5
    trait2:
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
beck_bed:
  seed: 46000
  N: 1000000
  phenotype:
    trait1:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 2.7745
        sigma: 0.623828
        prevalence:
          female: 0.072175
          male: 0.109686
      beta: 0.0
      beta_sex: 0.4581
    trait2:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 2.7745
        sigma: 0.623828
        prevalence:
          female: 0.072175
          male: 0.109686
      beta: 0.0
      beta_sex: 0.4581
  pedigree:
    trait1:
      C: 0.0
      E: 0.5
    trait2:
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
beck_bt:
  seed: 47000
  N: 1000000
  phenotype:
    trait1:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 3.21288
        sigma: 0.267314
        prevalence:
          female: 0.029795
          male: 0.003535
      beta: 0.0
      beta_sex: -0.4856
    trait2:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 3.21288
        sigma: 0.267314
        prevalence:
          female: 0.029795
          male: 0.003535
      beta: 0.0
      beta_sex: -0.4856
  pedigree:
    trait1:
      C: 0.0
      E: 0.5
    trait2:
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
beck_ca:
  seed: 48000
  N: 1000000
  phenotype:
    trait1:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 2.26905
        sigma: 0.715307
        prevalence:
          female: 0.006161
          male: 0.019493
      beta: 0.0
      beta_sex: 0.3077
    trait2:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 2.26905
        sigma: 0.715307
        prevalence:
          female: 0.006161
          male: 0.019493
      beta: 0.0
      beta_sex: 0.3077
  pedigree:
    trait1:
      C: 0.0
      E: 0.5
    trait2:
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
beck_cu:
  seed: 49000
  N: 1000000
  phenotype:
    trait1:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 3.16287
        sigma: 0.273653
        prevalence:
          female: 0.01212
          male: 0.0303
      beta: 0.0
      beta_sex: -0.4084
    trait2:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 3.16287
        sigma: 0.273653
        prevalence:
          female: 0.01212
          male: 0.0303
      beta: 0.0
      beta_sex: -0.4084
  pedigree:
    trait1:
      C: 0.0
      E: 0.5
    trait2:
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
beck_dep:
  seed: 50000
  N: 1000000
  phenotype:
    trait1:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 3.45363
        sigma: 0.467117
        prevalence:
          female: 0.156247
          male: 0.095105
      beta: 0.0
      beta_sex: -0.2702
    trait2:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 3.45363
        sigma: 0.467117
        prevalence:
          female: 0.156247
          male: 0.095105
      beta: 0.0
      beta_sex: -0.2702
  pedigree:
    trait1:
      C: 0.0
      E: 0.5
    trait2:
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
beck_ed:
  seed: 51000
  N: 1000000
  phenotype:
    trait1:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 3.0016
        sigma: 0.300346
        prevalence:
          female: 0.037471
          male: 0.002727
      beta: 0.0
      beta_sex: 0.4145
    trait2:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 3.0016
        sigma: 0.300346
        prevalence:
          female: 0.037471
          male: 0.002727
      beta: 0.0
      beta_sex: 0.4145
  pedigree:
    trait1:
      C: 0.0
      E: 0.5
    trait2:
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
beck_id:
  seed: 52000
  N: 1000000
  phenotype:
    trait1:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 3.14905
        sigma: 0.964654
        prevalence:
          female: 0.015062
          male: 0.020301
      beta: 0.0
      beta_sex: 0.5853
    trait2:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 3.14905
        sigma: 0.964654
        prevalence:
          female: 0.015062
          male: 0.020301
      beta: 0.0
      beta_sex: 0.5853
  pedigree:
    trait1:
      C: 0.0
      E: 0.5
    trait2:
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
beck_md:
  seed: 53000
  N: 1000000
  phenotype:
    trait1:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 3.45197
        sigma: 0.461638
        prevalence:
          female: 0.168367
          male: 0.105268
      beta: 0.0
      beta_sex: -0.2674
    trait2:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 3.45197
        sigma: 0.461638
        prevalence:
          female: 0.168367
          male: 0.105268
      beta: 0.0
      beta_sex: -0.2674
  pedigree:
    trait1:
      C: 0.0
      E: 0.5
    trait2:
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
beck_nss:
  seed: 54000
  N: 1000000
  phenotype:
    trait1:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 4.07936
        sigma: 0.679115
        prevalence:
          female: 0.236239
          male: 0.164327
      beta: 1.2663
      beta_sex: -0.413
    trait2:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 4.07936
        sigma: 0.679115
        prevalence:
          female: 0.236239
          male: 0.164327
      beta: 1.2663
      beta_sex: -0.413
  pedigree:
    trait1:
      C: 0.0
      E: 0.5
    trait2:
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
beck_ocd:
  seed: 55000
  N: 1000000
  phenotype:
    trait1:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 3.0876
        sigma: 0.503178
        prevalence:
          female: 0.024472
          male: 0.013837
      beta: 0.0
      beta_sex: 0.2187
    trait2:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 3.0876
        sigma: 0.503178
        prevalence:
          female: 0.024472
          male: 0.013837
      beta: 0.0
      beta_sex: 0.2187
  pedigree:
    trait1:
      C: 0.0
      E: 0.5
    trait2:
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
beck_pdd:
  seed: 56000
  N: 1000000
  phenotype:
    trait1:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 6.3747
        sigma: 1.32368
        prevalence:
          female: 0.02929
          male: 0.060095
      beta: 2.4569
      beta_sex: 1.3815
    trait2:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 6.3747
        sigma: 1.32368
        prevalence:
          female: 0.02929
          male: 0.060095
      beta: 2.4569
      beta_sex: 1.3815
  pedigree:
    trait1:
      C: 0.0
      E: 0.5
    trait2:
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
beck_sad:
  seed: 57000
  N: 1000000
  phenotype:
    trait1:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 3.60824
        sigma: 0.491508
        prevalence:
          female: 0.00287
          male: 0.001986
      beta: 0.0001
      beta_sex: -0.075
    trait2:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 3.60824
        sigma: 0.491508
        prevalence:
          female: 0.00287
          male: 0.001986
      beta: 0.0001
      beta_sex: -0.075
  pedigree:
    trait1:
      C: 0.0
      E: 0.5
    trait2:
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
beck_sch:
  seed: 58000
  N: 1000000
  phenotype:
    trait1:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 3.29561
        sigma: 0.339876
        prevalence:
          female: 0.017574
          male: 0.021816
      beta: 0.0
      beta_sex: -0.1507
    trait2:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 3.29561
        sigma: 0.339876
        prevalence:
          female: 0.017574
          male: 0.021816
      beta: 0.0
      beta_sex: -0.1507
  pedigree:
    trait1:
      C: 0.0
      E: 0.5
    trait2:
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
beck_spd:
  seed: 59000
  N: 1000000
  phenotype:
    trait1:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 3.26766
        sigma: 0.304928
        prevalence:
          female: 0.072013
          male: 0.031209
      beta: 0.0
      beta_sex: -0.4436
    trait2:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 3.26766
        sigma: 0.304928
        prevalence:
          female: 0.072013
          male: 0.031209
      beta: 0.0
      beta_sex: -0.4436
  pedigree:
    trait1:
      C: 0.0
      E: 0.5
    trait2:
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
beck_srd:
  seed: 60000
  N: 1000000
  phenotype:
    trait1:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 3.33094
        sigma: 0.424545
        prevalence:
          female: 0.041309
          male: 0.04545
      beta: 0.0
      beta_sex: -0.0802
    trait2:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 3.33094
        sigma: 0.424545
        prevalence:
          female: 0.041309
          male: 0.04545
      beta: 0.0
      beta_sex: -0.0802
  pedigree:
    trait1:
      C: 0.0
      E: 0.5
    trait2:
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
beck_su:
  seed: 61000
  N: 1000000
  phenotype:
    trait1:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 3.5622
        sigma: 0.449406
        prevalence:
          female: 0.041511
          male: 0.077669
      beta: 0.0
      beta_sex: 0.1269
    trait2:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 3.5622
        sigma: 0.449406
        prevalence:
          female: 0.041511
          male: 0.077669
      beta: 0.0
      beta_sex: 0.1269
  pedigree:
    trait1:
      C: 0.0
      E: 0.5
    trait2:
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
