demo_prev01:
  seed: 70001
  N: 500000
  G_ped: 8
  G_pheno: 6
  G_sim: 10
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.0
      E: 0.5
    trait2:
      A: 0.5
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.01
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.01
  censoring:
    gen_censoring: {}
    death_scale: 1000000
    death_rho: 1.0
demo_prev05:
  seed: 70002
  N: 500000
  G_ped: 8
  G_pheno: 6
  G_sim: 10
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.0
      E: 0.5
    trait2:
      A: 0.5
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.05
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.05
  censoring:
    gen_censoring: {}
    death_scale: 1000000
    death_rho: 1.0
demo_prev10:
  seed: 70003
  N: 500000
  G_ped: 8
  G_pheno: 6
  G_sim: 10
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.0
      E: 0.5
    trait2:
      A: 0.5
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.1
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.1
  censoring:
    gen_censoring: {}
    death_scale: 1000000
    death_rho: 1.0
demo_prev20:
  seed: 70004
  N: 500000
  G_ped: 8
  G_pheno: 6
  G_sim: 10
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.0
      E: 0.5
    trait2:
      A: 0.5
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.2
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.2
  censoring:
    gen_censoring: {}
    death_scale: 1000000
    death_rho: 1.0
demo_prev40:
  seed: 70005
  N: 500000
  G_ped: 8
  G_pheno: 6
  G_sim: 10
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.0
      E: 0.5
    trait2:
      A: 0.5
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.4
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.4
  censoring:
    gen_censoring: {}
    death_scale: 1000000
    death_rho: 1.0
demo_K1_prev20:
  seed: 70004
  N: 500000
  G_ped: 8
  G_pheno: 6
  G_sim: 10
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.0
      E: 0.5
    trait2:
      A: 0.5
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.2
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.2
  censoring:
    gen_censoring: {}
    death_scale: 1000000
    death_rho: 1.0
demo_K1_prev40:
  seed: 70005
  N: 500000
  G_ped: 8
  G_pheno: 6
  G_sim: 10
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.0
      E: 0.5
    trait2:
      A: 0.5
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.4
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.4
  censoring:
    gen_censoring: {}
    death_scale: 1000000
    death_rho: 1.0
demo_realistic:
  seed: 70010
  N: 500000
  G_ped: 8
  G_pheno: 6
  G_sim: 10
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.2
      E: 0.3
    trait2:
      A: 0.5
      C: 0.2
      E: 0.3
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.1
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.1
  censoring:
    gen_censoring:
      2:
      - 50
      - 80
      3:
      - 30
      - 80
      4:
      - 10
      - 80
      5:
      - 0
      - 80
      6:
      - 0
      - 60
      7:
      - 0
      - 40
    death_scale: 164
    death_rho: 2.73
demo_realistic_ref:
  seed: 70011
  N: 500000
  G_ped: 8
  G_pheno: 6
  G_sim: 10
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.2
      E: 0.3
    trait2:
      A: 0.5
      C: 0.2
      E: 0.3
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.1
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.1
  censoring:
    gen_censoring: {}
    death_scale: 1000000
    death_rho: 1.0
