ebias_ltm_K01_C0_nocensor:
  seed: 50001
  N: 500000
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.0
      E: 0.5
    trait2:
      A: 0.5
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.01
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.01
  censoring:
    gen_censoring: {}
    death_scale: 1000000
    death_rho: 1.0
ebias_ltm_K01_C0_death:
  seed: 50002
  N: 500000
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.0
      E: 0.5
    trait2:
      A: 0.5
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.01
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.01
  censoring:
    gen_censoring: {}
    death_scale: 164
    death_rho: 2.73
ebias_ltm_K01_C0_window:
  seed: 50003
  N: 500000
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.0
      E: 0.5
    trait2:
      A: 0.5
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.01
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.01
  censoring:
    gen_censoring:
      3:
      - 20
      - 60
      4:
      - 20
      - 60
      5:
      - 20
      - 60
    death_scale: 1000000
    death_rho: 1.0
ebias_ltm_K01_C0_both:
  seed: 50004
  N: 500000
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.0
      E: 0.5
    trait2:
      A: 0.5
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.01
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.01
  censoring:
    gen_censoring:
      3:
      - 20
      - 60
      4:
      - 20
      - 60
      5:
      - 20
      - 60
    death_scale: 164
    death_rho: 2.73
ebias_ltm_K05_C0_nocensor:
  seed: 50005
  N: 500000
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.0
      E: 0.5
    trait2:
      A: 0.5
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.05
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.05
  censoring:
    gen_censoring: {}
    death_scale: 1000000
    death_rho: 1.0
ebias_ltm_K05_C0_death:
  seed: 50006
  N: 500000
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.0
      E: 0.5
    trait2:
      A: 0.5
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.05
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.05
  censoring:
    gen_censoring: {}
    death_scale: 164
    death_rho: 2.73
ebias_ltm_K05_C0_window:
  seed: 50007
  N: 500000
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.0
      E: 0.5
    trait2:
      A: 0.5
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.05
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.05
  censoring:
    gen_censoring:
      3:
      - 20
      - 60
      4:
      - 20
      - 60
      5:
      - 20
      - 60
    death_scale: 1000000
    death_rho: 1.0
ebias_ltm_K05_C0_both:
  seed: 50008
  N: 500000
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.0
      E: 0.5
    trait2:
      A: 0.5
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.05
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.05
  censoring:
    gen_censoring:
      3:
      - 20
      - 60
      4:
      - 20
      - 60
      5:
      - 20
      - 60
    death_scale: 164
    death_rho: 2.73
ebias_ltm_K10_C0_nocensor:
  seed: 50009
  N: 500000
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.0
      E: 0.5
    trait2:
      A: 0.5
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.1
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.1
  censoring:
    gen_censoring: {}
    death_scale: 1000000
    death_rho: 1.0
ebias_ltm_K10_C0_death:
  seed: 50010
  N: 500000
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.0
      E: 0.5
    trait2:
      A: 0.5
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.1
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.1
  censoring:
    gen_censoring: {}
    death_scale: 164
    death_rho: 2.73
ebias_ltm_K10_C0_window:
  seed: 50011
  N: 500000
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.0
      E: 0.5
    trait2:
      A: 0.5
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.1
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.1
  censoring:
    gen_censoring:
      3:
      - 20
      - 60
      4:
      - 20
      - 60
      5:
      - 20
      - 60
    death_scale: 1000000
    death_rho: 1.0
ebias_ltm_K10_C0_both:
  seed: 50012
  N: 500000
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.0
      E: 0.5
    trait2:
      A: 0.5
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.1
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.1
  censoring:
    gen_censoring:
      3:
      - 20
      - 60
      4:
      - 20
      - 60
      5:
      - 20
      - 60
    death_scale: 164
    death_rho: 2.73
ebias_ltm_K20_C0_nocensor:
  seed: 50013
  N: 500000
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.0
      E: 0.5
    trait2:
      A: 0.5
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.2
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.2
  censoring:
    gen_censoring: {}
    death_scale: 1000000
    death_rho: 1.0
ebias_ltm_K20_C0_death:
  seed: 50014
  N: 500000
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.0
      E: 0.5
    trait2:
      A: 0.5
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.2
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.2
  censoring:
    gen_censoring: {}
    death_scale: 164
    death_rho: 2.73
ebias_ltm_K20_C0_window:
  seed: 50015
  N: 500000
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.0
      E: 0.5
    trait2:
      A: 0.5
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.2
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.2
  censoring:
    gen_censoring:
      3:
      - 20
      - 60
      4:
      - 20
      - 60
      5:
      - 20
      - 60
    death_scale: 1000000
    death_rho: 1.0
ebias_ltm_K20_C0_both:
  seed: 50016
  N: 500000
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.0
      E: 0.5
    trait2:
      A: 0.5
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.2
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.2
  censoring:
    gen_censoring:
      3:
      - 20
      - 60
      4:
      - 20
      - 60
      5:
      - 20
      - 60
    death_scale: 164
    death_rho: 2.73
ebias_ltm_K40_C0_nocensor:
  seed: 50017
  N: 500000
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.0
      E: 0.5
    trait2:
      A: 0.5
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.4
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.4
  censoring:
    gen_censoring: {}
    death_scale: 1000000
    death_rho: 1.0
ebias_ltm_K40_C0_death:
  seed: 50018
  N: 500000
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.0
      E: 0.5
    trait2:
      A: 0.5
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.4
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.4
  censoring:
    gen_censoring: {}
    death_scale: 164
    death_rho: 2.73
ebias_ltm_K40_C0_window:
  seed: 50019
  N: 500000
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.0
      E: 0.5
    trait2:
      A: 0.5
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.4
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.4
  censoring:
    gen_censoring:
      3:
      - 20
      - 60
      4:
      - 20
      - 60
      5:
      - 20
      - 60
    death_scale: 1000000
    death_rho: 1.0
ebias_ltm_K40_C0_both:
  seed: 50020
  N: 500000
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.0
      E: 0.5
    trait2:
      A: 0.5
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.4
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.4
  censoring:
    gen_censoring:
      3:
      - 20
      - 60
      4:
      - 20
      - 60
      5:
      - 20
      - 60
    death_scale: 164
    death_rho: 2.73
ebias_ltm_K01_C02_nocensor:
  seed: 50021
  N: 500000
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.2
      E: 0.3
    trait2:
      A: 0.5
      C: 0.2
      E: 0.3
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.01
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.01
  censoring:
    gen_censoring: {}
    death_scale: 1000000
    death_rho: 1.0
ebias_ltm_K05_C02_nocensor:
  seed: 50022
  N: 500000
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.2
      E: 0.3
    trait2:
      A: 0.5
      C: 0.2
      E: 0.3
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.05
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.05
  censoring:
    gen_censoring: {}
    death_scale: 1000000
    death_rho: 1.0
ebias_ltm_K10_C02_nocensor:
  seed: 50023
  N: 500000
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.2
      E: 0.3
    trait2:
      A: 0.5
      C: 0.2
      E: 0.3
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.1
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.1
  censoring:
    gen_censoring: {}
    death_scale: 1000000
    death_rho: 1.0
ebias_ltm_K20_C02_nocensor:
  seed: 50024
  N: 500000
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.2
      E: 0.3
    trait2:
      A: 0.5
      C: 0.2
      E: 0.3
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.2
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.2
  censoring:
    gen_censoring: {}
    death_scale: 1000000
    death_rho: 1.0
ebias_ltm_K40_C02_nocensor:
  seed: 50025
  N: 500000
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.2
      E: 0.3
    trait2:
      A: 0.5
      C: 0.2
      E: 0.3
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.4
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.4
  censoring:
    gen_censoring: {}
    death_scale: 1000000
    death_rho: 1.0
ebias_weibull_K10_C0_nocensor:
  seed: 50026
  N: 500000
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.0
      E: 0.5
    trait2:
      A: 0.5
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: frailty
      params:
        distribution: weibull
        scale: 70
        rho: 2.0
    trait2:
      model: frailty
      params:
        distribution: weibull
        scale: 70
        rho: 2.0
  censoring:
    gen_censoring: {}
    death_scale: 1000000
    death_rho: 1.0
ebias_cure_K10_C0_nocensor:
  seed: 50027
  N: 500000
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.0
      E: 0.5
    trait2:
      A: 0.5
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: cure_frailty
      params:
        distribution: weibull
        scale: 2160
        rho: 0.8
        prevalence: 0.1
    trait2:
      model: cure_frailty
      params:
        distribution: weibull
        scale: 2160
        rho: 0.8
        prevalence: 0.1
  censoring:
    gen_censoring: {}
    death_scale: 1000000
    death_rho: 1.0
ebias_cox_K10_C0_nocensor:
  seed: 50028
  N: 500000
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.0
      E: 0.5
    trait2:
      A: 0.5
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: cox
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.1
    trait2:
      model: adult
      params:
        method: cox
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.1
  censoring:
    gen_censoring: {}
    death_scale: 1000000
    death_rho: 1.0
