ebias_ltm_K01_C0_nocensor_2M:
  seed: 50101
  N: 2000000
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.0
      E: 0.5
    trait2:
      A: 0.5
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.01
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.01
  censoring:
    gen_censoring: {}
    death_scale: 1000000
    death_rho: 1.0
ebias_ltm_K05_C0_nocensor_2M:
  seed: 50102
  N: 2000000
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.0
      E: 0.5
    trait2:
      A: 0.5
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.05
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.05
  censoring:
    gen_censoring: {}
    death_scale: 1000000
    death_rho: 1.0
ebias_ltm_K10_C0_nocensor_2M:
  seed: 50103
  N: 2000000
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.0
      E: 0.5
    trait2:
      A: 0.5
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.1
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.1
  censoring:
    gen_censoring: {}
    death_scale: 1000000
    death_rho: 1.0
ebias_ltm_K20_C0_nocensor_2M:
  seed: 50104
  N: 2000000
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.0
      E: 0.5
    trait2:
      A: 0.5
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.2
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.2
  censoring:
    gen_censoring: {}
    death_scale: 1000000
    death_rho: 1.0
ebias_ltm_K40_C0_nocensor_2M:
  seed: 50105
  N: 2000000
  replicates: 1
  pedigree:
    p_mztwin: 0
    trait1:
      A: 0.5
      C: 0.0
      E: 0.5
    trait2:
      A: 0.5
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.4
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 50
        cip_k: 0.15
        prevalence: 0.4
  censoring:
    gen_censoring: {}
    death_scale: 1000000
    death_rho: 1.0
