ADHD_AUT_increaseE:
  seed: 50000
  replicates: 3
  N: 1000000
  G_sim: 10
  G_ped: 8
  G_pheno: 6
  pedigree:
    trait1:
      A: 0.5
      C: 0.0
      E:
        0: 0.3
        3: 0.35
        4: 0.4
        5: 0.45
        6: 0.5
        7: 0.55
        8: 0.6
        9: 0.65
    trait2:
      A: 0.5
      C: 0.0
      E:
        0: 0.3
        3: 0.35
        4: 0.4
        5: 0.45
        6: 0.5
        7: 0.55
        8: 0.6
        9: 0.65
    rA: 0.0
    rC: 0.0
    rE: 0.0
  standardize: true
  phenotype:
    trait1:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 2.88737
        sigma: 0.658447
        prevalence:
          female: 0.048193
          male: 0.083224
      beta: 0.0
      beta_sex: 0.5003
    trait2:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 3.86639
        sigma: 0.477996
        prevalence:
          female: 0.028329
          male: 0.051935
      beta: 0.0
      beta_sex: 0.1122
  censoring:
    gen_censoring:
      0:
      - 80
      - 80
      1:
      - 80
      - 80
      2:
      - 60
      - 80
      3:
      - 40
      - 80
      4:
      - 0
      - 80
      5:
      - 0
      - 60
      6:
      - 0
      - 35
      7:
      - 0
      - 20
ADHD_AUT_increaseE_nostd:
  seed: 50000
  replicates: 3
  N: 1000000
  G_sim: 10
  G_ped: 8
  G_pheno: 6
  pedigree:
    trait1:
      A: 0.5
      C: 0.0
      E:
        0: 0.3
        3: 0.35
        4: 0.4
        5: 0.45
        6: 0.5
        7: 0.55
        8: 0.6
        9: 0.65
    trait2:
      A: 0.5
      C: 0.0
      E:
        0: 0.3
        3: 0.35
        4: 0.4
        5: 0.45
        6: 0.5
        7: 0.55
        8: 0.6
        9: 0.65
    rA: 0.0
    rC: 0.0
    rE: 0.0
  standardize: false
  phenotype:
    trait1:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 2.88737
        sigma: 0.658447
        prevalence:
          female: 0.048193
          male: 0.083224
      beta: 0.0
      beta_sex: 0.5003
    trait2:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 3.86639
        sigma: 0.477996
        prevalence:
          female: 0.028329
          male: 0.051935
      beta: 0.0
      beta_sex: 0.1122
  censoring:
    gen_censoring:
      0:
      - 80
      - 80
      1:
      - 80
      - 80
      2:
      - 60
      - 80
      3:
      - 40
      - 80
      4:
      - 0
      - 80
      5:
      - 0
      - 60
      6:
      - 0
      - 35
      7:
      - 0
      - 20
