long_term:
  replicates: 1
  seed: 1879
  pedigree:
    trait1:
      C: 0.0
      E: 0.5
    trait2:
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
  N: 200000
  G_sim: 35
  G_ped: 30
  G_pheno: 30
  censoring:
    gen_censoring:
      0:
      - 0
      - 80
long_solmi_mood:
  replicates: 1
  seed: 1880
  pedigree:
    trait1:
      C: 0.0
      E: 0.5
    trait2:
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
  N: 200000
  G_sim: 35
  G_ped: 30
  G_pheno: 30
  censoring:
    gen_censoring:
      0:
      - 0
      - 80
  phenotype:
    trait1:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 3.58381
        sigma: 0.62896
        prevalence: 0.15
      beta: 0.1749
    trait2:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 3.58381
        sigma: 0.62896
        prevalence: 0.15
      beta: 0.1749
long_beck_adhd:
  replicates: 1
  seed: 1881
  pedigree:
    trait1:
      C: 0.0
      E: 0.5
    trait2:
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
  N: 200000
  G_sim: 35
  G_ped: 30
  G_pheno: 30
  censoring:
    gen_censoring:
      0:
      - 0
      - 80
  phenotype:
    trait1:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 2.88747
        sigma: 0.658443
        prevalence:
          female: 0.0481943
          male: 0.083224
      beta: 0.0
      beta_sex: 0.5009
    trait2:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 2.88747
        sigma: 0.658443
        prevalence:
          female: 0.0481943
          male: 0.083224
      beta: 0.0
      beta_sex: 0.5009
