solmi_neurodevelopmental:
  seed: 30042
  N: 1000000
  phenotype:
    trait1:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 2.35342
        sigma: 0.710781
        prevalence: 0.08
      beta: 0.0
    trait2:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 2.35342
        sigma: 0.710781
        prevalence: 0.08
      beta: 0.0
  pedigree:
    trait1:
      C: 0.0
      E: 0.5
    trait2:
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
solmi_anxiety:
  seed: 31042
  N: 1000000
  phenotype:
    trait1:
      model: adult
      params:
        method: cox
        cip_x0: 17.4982
        cip_k: 0.119542
        prevalence: 0.15
      beta: 0.751962
    trait2:
      model: adult
      params:
        method: cox
        cip_x0: 17.4982
        cip_k: 0.119542
        prevalence: 0.15
      beta: 0.751962
  pedigree:
    trait1:
      C: 0.0
      E: 0.5
    trait2:
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
solmi_ocd:
  seed: 32042
  N: 1000000
  phenotype:
    trait1:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 2.98502
        sigma: 0.549797
        prevalence: 0.025
      beta: 0.0
    trait2:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 2.98502
        sigma: 0.549797
        prevalence: 0.025
      beta: 0.0
  pedigree:
    trait1:
      C: 0.0
      E: 0.5
    trait2:
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
solmi_eating:
  seed: 33042
  N: 1000000
  phenotype:
    trait1:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 2.91098
        sigma: 0.317321
        prevalence: 0.03
      beta: 0.0
    trait2:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 2.91098
        sigma: 0.317321
        prevalence: 0.03
      beta: 0.0
  pedigree:
    trait1:
      C: 0.0
      E: 0.5
    trait2:
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
solmi_stress:
  seed: 34042
  N: 1000000
  phenotype:
    trait1:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 8.0
        sigma: 1.49059
        prevalence: 0.07
      beta: 3.4573
    trait2:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 8.0
        sigma: 1.49059
        prevalence: 0.07
      beta: 3.4573
  pedigree:
    trait1:
      C: 0.0
      E: 0.5
    trait2:
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
solmi_substance_use:
  seed: 35042
  N: 1000000
  phenotype:
    trait1:
      model: cure_frailty
      params:
        distribution: loglogistic
        scale: 26.9111
        shape: 3.10664
        prevalence: 0.12
      beta: 0.0
    trait2:
      model: cure_frailty
      params:
        distribution: loglogistic
        scale: 26.9111
        shape: 3.10664
        prevalence: 0.12
      beta: 0.0
  pedigree:
    trait1:
      C: 0.0
      E: 0.5
    trait2:
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
solmi_schizophrenia:
  seed: 36042
  N: 1000000
  phenotype:
    trait1:
      model: adult
      params:
        method: ltm
        cip_x0: 22.3464
        cip_k: 0.304667
        prevalence: 0.01
      beta: 0.96043
    trait2:
      model: adult
      params:
        method: ltm
        cip_x0: 22.3464
        cip_k: 0.304667
        prevalence: 0.01
      beta: 0.96043
  pedigree:
    trait1:
      C: 0.0
      E: 0.5
    trait2:
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
solmi_personality:
  seed: 37042
  N: 1000000
  phenotype:
    trait1:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 3.2367
        sigma: 0.350747
        prevalence: 0.1
      beta: 0.0
    trait2:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 3.2367
        sigma: 0.350747
        prevalence: 0.1
      beta: 0.0
  pedigree:
    trait1:
      C: 0.0
      E: 0.5
    trait2:
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
solmi_mood:
  seed: 38042
  N: 1000000
  phenotype:
    trait1:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 4.83164
        sigma: 0.884423
        prevalence: 0.15
      beta: 1.5745
    trait2:
      model: cure_frailty
      params:
        distribution: lognormal
        mu: 4.83164
        sigma: 0.884423
        prevalence: 0.15
      beta: 1.5745
  pedigree:
    trait1:
      C: 0.0
      E: 0.5
    trait2:
      C: 0.0
      E: 0.5
    rA: 0.0
    rC: 0.0
