name: simACE
channels:
  - nodefaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.13.*
  # core
  - numpy
  - scipy
  - pandas
  - pyarrow
  - pyyaml
  - numba
  # plotting
  - matplotlib
  - seaborn
  - pillow
  # workflow
  - snakemake
  - snakemake-executor-plugin-slurm
  - snakefmt
  # dev / test
  - pytest
  - ruff
  # notebook
  - jupyter
  - notebook
  # graphics
  - graphviz
  # MKL / linear algebra
  - libopenblas
  - mkl
  - tbb

  # system
  - pip
  # optional: for generating methods.pdf
  # - pandoc
  # - tectonic
  - pip:
      - "-e ..[dev]"
      - "-e ../fitACE[plot]"
variables:
  MPLBACKEND: Agg
