name: simACE
channels:
  - nodefaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.13.*
  # core
  - numpy=2.4.*
  - scipy=1.17.*
  - pandas=3.0.*
  - pyarrow=23.0.*
  - pyyaml=6.0.*
  - numba=0.65.*
  # plotting
  - matplotlib=3.10.*
  - seaborn=0.13.*
  - pillow=12.2.*
  # workflow
  - snakemake=9.20.*
  - snakemake-executor-plugin-slurm=2.6.*
  - snakefmt=1.1.*
  # dev / test
  - pytest=9.0.*
  - ruff=0.15.*
  # notebook
  - jupyter
  - notebook
  # graphics
  - graphviz
  # MKL / linear algebra
  - libopenblas
  - mkl
  - tbb

  # system
  - pip
  # optional: for generating methods.pdf
  # - pandoc
  # - tectonic
  - pip:
      - "-e ..[dev]"
      - "-e ../fitACE[plot]"
variables:
  MPLBACKEND: Agg
